### ISSUE TITLE
What font did you use in the PDF version of this document?

### ISSUE THREAD

**Issue by lcota** [jwiegley/git-from-the-bottom-up#11]
http://ftp.newartisans.com/pub/git.from.bottom.up.pdf

It looks amazing.

**Comment by markusboehme** [comment]
Looks like it's [Garamond](https://en.wikipedia.org/wiki/Garamond).

**Comment by jwiegley** [comment]
Yes, it is Adobe Garamond Premier Pro, which came with InDesign CS when I purchased it.  It is still my favorite print font to this day.  Thanks for noticing, @lcota!

**Comment by lcota** [comment]
It's a gorgeous font in a latex document!
