### ISSUE TITLE
Why CC:BY-NoDerivatives?

### ISSUE THREAD

**Issue by firegurafiku** [jwiegley/git-from-the-bottom-up#12]
Hi!

I thought of translating your document into Russian, but then I discovered that you have explicitly restricted derivative works by the license you've chosen. Translation into another language is surely a derivative work, so

* Is there a good reason to use a license of ND-kind?
* Is there anything I can do to translate the text in a lawful way?

**Comment by jwiegley** [comment]
Can you submit a pull request with the more liberal license?  I'd be happy to support you in translating the text to other languages.

**Comment by firegurafiku** [comment]
Which one would you prefer?
Here is the table from the Creative Commons FAQ featuring [possible relations][cc] between original work's license and derivative work's license.

![Creative Commons license for derivative works][img]

*(Legend: green cell — okay; yellow — not recommended, but technically possible; grey — not allowed.)*

Since you current license is BY-ND 4.0, I suggest switching to one of the following licenses:
* BY 4.0 — simply remove ND-restriction, derivative works still must clearly claim themselves as derivatives and make a proper attribution to the original work;
* BY-SA 4.0 — as above, but also forbid derivative works to pick a more restrictive license.

Please, respond with the name of the license you like the most, and I'll make a PR in a day or two.
And, just in case, note that none of BY-ND, BY, and BY-SA disallows commercial use.

[cc]: https://creativecommons.org/faq/#if-i-derive-or-adapt-material-offered-under-a-creative-commons-license-which-cc-licenses-can-i-use
[img]: https://cloud.githubusercontent.com/assets/1611416/21208601/665138be-c288-11e6-814c-195f8bed3b7d.png

**Comment by jwiegley** [comment]
I think BY 4.0 sounds good.
