### ISSUE TITLE
weird sentence in 'Taking the index further'

### ISSUE THREAD

**Issue by bitbonk** [jwiegley/git-from-the-bottom-up#14]
Im not a native English speaker but I think something is wrong about the sentence below (it's from this chapter https://github.com/jwiegley/git-from-the-bottom-up/blob/master/2-The-Index/2-taking-the-index-further.md)

> What you’d need to do something like this is an index which allows for greater depth than one commit at a time.

**Comment by bitbonk** [comment]
Nevermind I finally got it, I got hung up on "what you'd need to do", a better version of this sentence however would have been:
> To do something like this, you would need an index which allows for greater depth than one commit at a time.
>

**Comment by bitbonk** [comment]
I suppose this change will not show up on https://jwiegley.github.io/git-from-the-bottom-up/ because bitbook does not exist anymore? How/where can we get a nicely rendered version of this document?
An up to date PDF version would be nice too.

**Comment by jwiegley** [comment]
We'll have to look at how to create a nice PDF using pandoc, since I don't have any way to recreate what I had originally done to make the first PDF.

**Comment by bryanbraun** [comment]
It's a little more hassle, but if you submit a PR to change the html file in the `gh-pages` branch, it will get updated on https://jwiegley.github.io/git-from-the-bottom-up.
